import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import { ConnectButton } from "@rainbow-me/rainbowkit"
import Header from "../components/Header"
import Swap from "../components/Swap"

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>SolventSwap</title>
                <meta name="SolventSwap" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Swap />
        </div>
    )
}
