import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import { ConnectButton } from "@rainbow-me/rainbowkit"
import Header from "../components/Header"
import Swap from "../components/Swap"
import { MintTokens } from "../components/MintTokens"

export default function Home() {
    return (
        <div className={`${styles.container} min-h-screen bg-gradient-to-b from-blue-500 to-black`}>
            <Head>
                <title>SolventSwap</title>
                <meta name="SolventSwap" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Swap />
            <MintTokens />
        </div>
    )
}
