import React from "react"
import Header from "../components/Header"
import Head from "next/head"
import Pool from "../components/Pool"

const pools = () => {
    return (
        <div className="w-full">
            <div className="justify-center w-full h-auto max-w-screen-lg mx-auto">
                <Head>
                    <title>SolventSwap</title>
                    <meta name="SolventSwap" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Header />
                <Pool />
            </div>
        </div>
    )
}

export default pools
