import React from "react"
import Header from "../components/Header"
import Head from "next/head"
import Pool from "../components/Pool"
import styles from "../styles/Home.module.css"

const pools = () => {
    return (
        <div className={`${styles.container} min-h-screen bg-gradient-to-b from-blue-500 to-black`}>
            <div className="w-full">
                <div className="justify-center w-full h-auto max-w-screen-lg mx-auto">
                    <Head>
                        <title>SolventSwap</title>
                        <meta name="SolventSwap" content="Generated by create next app" />
                        <link rel="icon" href="/favicon.ico" />
                    </Head>
                    <Header />
                    <div className="mt-10 text-2xl text-center">In Development...</div>
                    {/* <Pool pairName="USDC/LINK" tvl={45} /> */}
                </div>
            </div>
        </div>
    )
}

export default pools
